a=input("Enter a string:")
print("Original string:",a)
print("Capitalized form:",a.capitalize())
print("Upper case:",a.upper())
print("Lower case:",a.lower())
print("Title:",a.title())
print("Swapcase:",a.swapcase())
print("Split:",a.split())
print("Substring count:",a.count('k'))
print("Replace:",a.replace('naidu','King'))
b=input("Enter another string:")
print("Join:",b.join(a))
print("Alpha or not:",a.isalpha())
print("Numeric:",a.isnumeric())
print("min:",min(a))